### ISSUE TITLE
Add additional installation methods

### ISSUE THREAD

**Issue by robbystk** [tectonic-typesetting/tectonic-typesetting.github.io#1]
[Issue #4 on the main repo](https://github.com/tectonic-typesetting/tectonic/issues/4) mentions `cargo install tectonic`, and the AUR as ways to install, and [Issue #32](https://github.com/tectonic-typesetting/tectonic/issues/32) mentions windows installation.  Let's add these to the installation page.

- [ ] `cargo install tectonic`
- [ ] AUR
- [ ] Windows

**Comment by pkgw** [comment]
These are all now mentioned in the latest revision I just pushed!

**Comment by dfalster** [comment]
Your package looks interesting. I use mac OSX and don't want to install homebrew. Do you have an option for building from source without having homebrew installed?

**Comment by pkgw** [comment]
@dfalster You're going to need to get `freetype`, `harfbuzz`, etc. installed one way or another. I'm sure that other systems like MacPorts provide all of these packages as well. If you can get your environment such that an invocation of `pkg-config` will get the right compiler flags for these libraries, a `cargo install` command should succeed.
