### ISSUE TITLE
Shell script does not download right archive on Windows

### ISSUE THREAD

**Issue by Baldomo** [tectonic-typesetting/tectonic-typesetting.github.io#46]
While the `drop-installer.sh` correctly detects Bash/MinGW/etc. on Windows, the archive extension is [hardcoded to `.tar.gz`](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/blob/e38cabbf26639506ceb968eda80adad4f360c939/support/drop-installer.sh#L42), which makes `curl` give a 404. Since Windows should be able to extract Gunzip archives, even with the preinstalled archive manager, I suppose one of the following could be done:
- Change archive extension for the Windows release archive from now on (but it won't work retroactively)
- Change the script so it also sets the archive extension when [detecting the OS type](https://github.com/tectonic-typesetting/tectonic-typesetting.github.io/blob/e38cabbf26639506ceb968eda80adad4f360c939/support/drop-installer.sh#L153), which would probably be easier

**Comment by pkgw** [comment]
I missed this originally and some discussion ensued in https://github.com/tectonic-typesetting/tectonic/issues/990 . But a fix will end up going into this repo, so let's try to anchor discussion here.
